leftnav:
- identifier: 71299574-6770-10f0-e5f3-184bd49a002a
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 92921548-1ff2-3f89-50fc-b1f2ccf6b03d
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9e42d62b-aac8-5921-1b61-3c436350ea9f
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 489078a1-9e7b-9a90-3b65-43d9f28ad334
  name: Discussion Questions
  pageRef: /pages/discussion-questions
  weight: 40
- identifier: 67681be5-308d-024f-ff64-2dd372c480dc
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 9c6774c1-76f8-237c-ab55-f001fbeee510
  name: Primary Sources
  pageRef: /pages/primary-sources/
  weight: 60
- identifier: de37ef0c-6387-2491-bf84-7d95cc732e0b
  name: Collections of Documents and Sources (18th Century)
  pageRef: /pages/primary-sources/documents-and-sources
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 70
- identifier: ce829ed7-fcf8-951f-ed2e-65916eac1710
  name: Important Fiction with a Political Edge
  pageRef: /pages/primary-sources/important-fiction-with-a-political-edge
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 80
- identifier: f566e24c-9f45-c6f6-2c1d-dac6f1634c82
  name: Political Philosophy
  pageRef: /pages/primary-sources/political-philosophy
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 90
- identifier: 1db6d4e2-c130-bc25-f032-a98acfaa7273
  name: Russia's Imperial Presence
  pageRef: /pages/primary-sources/russias-imperial-presence
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 100
- identifier: bb40c0bd-de8b-b795-4150-d140955ab32c
  name: Peasants and the Countryside
  pageRef: /pages/primary-sources/peasants-and-the-countryside
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 110
- identifier: 3f3e513f-5307-0988-bc64-daf8ccc89b0d
  name: Women's Letters and Memoirs (and Other Writings)
  pageRef: /pages/primary-sources/womens-letters-and-memoirs-and-other-writings
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 120
- identifier: aaf2a868-8a23-d173-3d7a-f07b31fd3fb9
  name: Peter the Great
  pageRef: /pages/primary-sources/peter-the-great
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 130
- identifier: 0bfae20f-79cf-ea63-f7d7-dabf3c3ec3d9
  name: Men's Memoirs, Literature, and Letters
  pageRef: /pages/primary-sources/mens-memoirs-literature-and-letters
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 140
- identifier: eefa223f-5956-5ec5-009f-af7fa6222e92
  name: Diplomacy
  pageRef: /pages/primary-sources/diplomacy
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 150
- identifier: b728cc57-61d5-c79b-cb24-4c4119ea57e6
  name: Religion
  pageRef: /pages/primary-sources/religion
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 160
- identifier: f32f4211-801e-8f80-66ec-9c6161c0b15b
  name: Medicine
  pageRef: /pages/primary-sources/medicine
  parent: 9c6774c1-76f8-237c-ab55-f001fbeee510
  weight: 170
- identifier: 60db2407-3329-4f13-cfc9-94c0d0bf75f1
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 180
